# Generated by Django 3.0.8 on 2020-07-24 18:28
from __future__ import unicode_literals
from django.db import migrations, models
from django.contrib.auth import get_user_model

def forwards_func(apps, schema_editor):
	credentials = {
			'username': 'Samir',
			'email' : 'samir@legendary.com',
			'password': 'qwerty12345*',
			'is_superuser': True}
	get_user_model().objects.create_superuser(**credentials)

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_user_isadmin'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
