"""empty message

Revision ID: 30f11e16975b
Revises:
Create Date: 2020-10-23 13:47:10.739239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f11e16975b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mail', sa.String(length=50), nullable=False),
        sa.Column('author_name', sa.String(length=50), nullable=False),
        sa.Column('approved_articles', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mail')
        )
    op.create_table(
        'articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('approved', sa.Boolean(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###

    op.execute('ALTER TABLE articles DROP CONSTRAINT articles_author_id_fkey;')
    op.execute(
        'ALTER TABLE articles \
        ADD CONSTRAINT articles_author_id_fkey \
        FOREIGN KEY (author_id) \
        REFERENCES authors(id) \
        ON UPDATE CASCADE ON DELETE CASCADE;'
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('authors')
    # ### end Alembic commands ###
