"""empty message

Revision ID: b6f014558fa3
Revises: 30f11e16975b
Create Date: 2020-10-24 14:38:30.886683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f014558fa3'
down_revision = '30f11e16975b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('articles_author_id_fkey', 'articles', type_='foreignkey')
    # op.create_foreign_key(None, 'articles', 'authors', ['author_id'], ['id'])
    op.add_column('authors', sa.Column('name', sa.String(length=50), nullable=True))
    op.execute('UPDATE authors SET name = author_name')
    op.alter_column('authors', 'name', nullable=False)
    op.drop_column('authors', 'author_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('author_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.execute('UPDATE authors SET author_name = name')
    op.alter_column('authors', 'author_name', nullable=False)
    op.drop_column('authors', 'name')
    # op.drop_constraint(None, 'articles', type_='foreignkey')
    # op.create_foreign_key('articles_author_id_fkey', 'articles', 'authors', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
